### ISSUE TITLE
fix: existing search component

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/CWBN#80]
references:
https://github.com/Day8/re-com/blob/master/src/re_demo/typeahead.cljs
https://re-com.day8.com.au/#/typeahead

**Comment by galbwe** [comment]
I made a branch called search-bar for this issue.

**Comment by galbwe** [comment]
Should we close this, since I accidentally pushed a separate branch for the search bar?

**Comment by dviramontes** [comment]
@galbwe yes closing...
