### ISSUE TITLE
feat: sub-category navigation

### ISSUE THREAD

**Issue by dviramontes** [codefordenver/CWBN#95]
![2018-09-29 at 12.18 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5459c18accdf21020031d221/125516c66e82c728ace21e0d46bac4cb7bcfd3f0c2bbe603a549b0c57b08762b69348e693cc7f33ab0487e021b4d44be44090b11fbab8d23a2b46825dc0f0bedd03f5c76906f17aaaa9e0dfd50e474d412dcfce9c85ecafa3f25ed8a8a4c361c011d8df75f32a5905985.png)

AC:
- Add ability to click on sub-category and filter down selection
- Sub selection should be toggle-able ( if unselected - org count should also reset)

**Comment by AlanPeters** [comment]
I should be able to have this done by Monday if no one else is working on it.
